services:
  chattyStore:
    image: postgres:15
    container_name: postgres-chatty
    environment:
      POSTGRES_USER: chatty
      POSTGRES_PASSWORD: chatty
      POSTGRES_DB: chatty-store
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nature-gift-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatty -d chatty-store"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {}

networks:
  nature-gift-network:
    driver: bridge
